BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
	XXX XXXXXXXX X XXXXXX XXXXXXXXXXXX XXX XXXXXXXXXX XXXXX XXXXX X XX XXXXXXXXX XXXX XX XXXXXX
	XXX XXXXXXXXX X XXXXXX
	XXX XXXXXXXXXXXXXXXX X XXXXXX
	XXX XXXXXX X XX XXXXXXXX XXX XXXXX
	XXX XXXXX X XXX XXXXXXXXXX XXXXXXX XXXXXX
	XXX XXXXXX X XXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX
	XXX XXXXX X XXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXX
	XXX XXXXXX X XXX XXXXXXXXXX XXXXXXX XXXXXX
	XXX XXXXXX X XXX XXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX
	XXX XXXX X XXXXXXX XXXX XXXXXXXXX  X XXXX
	XXX XXXX X XXXXX
	XXX XXXX X XXXXXX
	XXX XXXX X XXXXXX
	XXX XXXXXXXXXXXXXX X XX
	XXX XXXXXXXXXX X XXX
	XXX XXXXXXXXXXX X XXXXXX
	XXX XXXXXXXXXX X XXXXXX XX XXXX XXXX
	XXX XXXXXXXXXXXXXXXXXXX X XXXXXXX XX XXXX XXXXXXXXX XXXX
	XXX XXXXXXXXXXX X XXXXXXXX XX XXXX XXXXXXXXX
	XXX XXXXXXXXXXX X XXXXXXXX XX XXXX XXXX
	XXX XXXXXXXXXX X XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXX
	XXX XXXXXXXXXXXX X XX
	XXX XXXXXXXXXXX X XXXXXXXXX
	XXX XXX X XXXXXXXX
	XXX XXXXXXX X XXX
	XXX XXXXX X XXX
	XXX XXXXX X XXX
	XXX XXXX
	XX XXX XXXX X X
	XX 		XXXX XXXXXXXXXX X
	XX 			XXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
	XX 		XX
	XX 		XXXX X
	XX 			XXXX XXXXXXXXXX X

	XX 			X
	XX 		X
	XX 	X
	XXXXXXXXXXX XXXXXXXXXX XXXXX XX X XXXX XXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXX
	XX XXXXXXX XXXXXXXXXXX XXXXX XXX X XXXX
	XX XXXXXXXX XXXXXXX XXXXXXXXXX XXXXX XXXXX XXX XXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
	XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX X
			XXXXXX XXXXXX
		XXX
		XXXXXXXXXXX XXXXXXX XXXXXXXX XXX XXXXXXXXX
		XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXX XXXXX X XXXXXXXXX XXXXXXXX XXXXX XX XX XXXXXXXX
		XX XXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX  XX XXXXXX XXXXXXX XXX XXXXXXXXX XXXXXX X XXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXX XXX XXXXXXXXX XXXXXX X XXXXXX
		XXXXXXXXXXXXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXX XXXXXXXX X X XXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XX XXXXXX X XXX X XXXXXXXXXXXXXX
			XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXXXXXXXXX
			XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X XXXXXXXXXX XXX
			XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXX XXXXXX XXXXXXXXX
		XXX

		
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX	
			XX XXXXXXXXXXX X
				XXXXXXXXXXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXX
			XXXXXXXXXXX
			XXXXXXXXXX
			XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXXXXXXXXX
			XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X XXXXXXXXXX XXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
			XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX  X XXXXXXXXXXXXXXXXXX
			XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
			XXX XXXXX X XXXXXXXXXXXX
   			XXX XXXXXX X XXXXXXXXXXXXX
   			XXX XXXXXX X X
   				XXXXXX XX
   				XXXXXXX XX
   				XXX XXXXXXXXXXX
   					XXXXXXXXXXXXXXXXXXX X X XXXXXXXXXX X X XXXXXXX X X XXXXXXXXXXXX
   				X
   			X
		    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
		        XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
		        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
		        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
		        XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
		        XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXX
		        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
		        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXX
		        XX XXXXXX XXXXXX XXXXXXXXX
		        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
		            XXXX XXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXXXXX
		                XXXXXX
		            XXXX XXXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXXXXXX
		                XXXXXX
		            XXXX XXXXXXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXXX
		                XXXXXX
		            XXXX XXXXXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXXXXXX
		                XXXXXXXXXXXXXXXXXXXXXX
		                XXXXXX
		        X
		        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		        XXX XXXXX X XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
		        XXX XXXXXX X XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
		        XXXXXXXX XX XXXXXXX X
		            XXXXXXXXXXXXXXXXXXX
		            XXXXXXXXXXXXXXXXXXXXX
		        X
		        XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
		        XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
		        XXXXXXXXXXXX

		    X
		    XXXXXXXX XXXXXXXXXXXXXXXX XX XX XXXXX X
		        XXX XXXXX X XXXXXXXXXXXXXXXXX
		        XXX XXXXX X XXXXXXXXXXXXXXXXX
		        XXX XXXXXX X XXX XXXXXXXXXXXXXX
		            XX XX
		            XX XX
		            XXXXXXX XXXXXXX
		            XXXXX XXXXXXX
		            XXXXXXXXXXXX XX
		            XXXXXXX XX
		            XXXXX XXXXX
		            XXXXXXXXXX XXXXX
		            XXXXXXXXXX XXXXXX
		        XXX
		        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
		            XXXXXXXXXXXXX
		            XXXXXXXXXXXXX
		        XXX
		        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX X
		            XXXXXXXXXXXXXXXXXXXXXXXXX
		            XXXXXXXXXXXXXXXXX
		        	
		        XXX
		        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
		            XXXXXXXXXXXXXXXXXXXXXXXXX
		            XXXXXXXXXXXXX
		        XXX
		        XX XXX XXXXX XXXXXXX
		        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
		            XXX XXXXX X XXXXXXXXXXXXXXXX
		            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
		            XXXXXXXXXXXXXXXXXXXXXXX

		            XXXXXXXXXXXXX

		        XXX
		        XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
		            XXX XXXXX X XXXXXXXXXXXXXXXX
		            XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
		            XXXXXXXXXXXXXXXXXXXXXXX
		            XXXXXXXXXXXXX
		        XXX
		        XXXXXXXXXXXXXXXXXX
		    X
		    XXX XXXXX X XXX XXXXXXXXXXXXX
		        XXXXXXXXXX XXXXXXXXXXXX
		        XXXXXX XXXXXX
		        XXXXXXX XXXXXX
		    XXX
		    XXX XXXXX X XXX XXXXXXXXXXXXXX
		    XXXXXXXXXXXXXXXXX
		    XXX XXXXXX X XXX XXXXXXXXXXXXX
		        XXXXXX XXXX
		        XXXXXXX XXX
		    XXX
		    XXX XXXXXXXXXXX X XXX XXXXXXXXXXXXX
		        XX XXXX
		        XX XXX
		        XXXXXXXXXX XXXXX
		    XXX
		    XXX XXXX X X
		    	XX XX
		    	XX X
		    X
		    XXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
		        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X X X XXXXXXXXXXXXXXXXXXXXX
				XXX XXXXX X X
					XX XXXXXXXXXXX
						XXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X X 
					XX
					XX XXXXXXXXXXX
						XXXXXX XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X X
					X
				X
				XXXXXXXXXXXXXXXXXXXXX X X X X X XXXXXXXXXX
				XXXXXXXXX XXXXXXX X XXXXX XXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX

				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX

		    XXX
		    XXXXXXXXXXXXXXXXXXXXXXX
		    XXXXXXXXXXXXXXXXXXXXXXXX
		    XXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXX
		    XXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXXXX
		    XXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX
		    XXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXXXXX
		    XXX X XXXXXXXXXXXXXX
		        XXX XXXXXXXXX X XXX XXXXXXXX
			    XXXXXXXXXXXXXXXX X XXXXXXXXXX X
			        XXXXXXXXXXXXXXXXXXXXXXXX
			        XXXXXXXXXXXXX
			        XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
		        	XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
		        	XXXXXXXXXXXX	
			    XX
		  	  XXXXXXXXXXXXX X XXXX
			X
		    XXXXXXXXXXXXXXXXXXXXX
		    	XXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXX
		    	XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
		    XXX
			XXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXX
		XXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
			XXXXXXXXXXXX
			XXXXXXXXXXXXX
		XXX

		XXXXXXXXX XXXXXXXXXXX XXX XXXXXX
		XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXX XX XXXXXXXXXXXX XXXX XXXXX XX XXXXXXXXXXXXX
		XX XXXXXXX XXX XXXXXXXX XXXXXX
		XXX XXXXXXXXXX
		XXXXXXXX XXXXXXXXXXXX
			BB BBBBBBBBBBBBBBBBB
				XXX XXXXXXXXXXXXX X XXX XXXXX XXXXXXXX XXXXXXXXXXX
				XX XXX XX X XXXX
				XX 	XX X XXXX
				XXX X X XXXXXXXXXXX
					X X XXXXXXXXXXX
				XXX XXXXX X XXXXXXXXXXX
					XXXXXX X XXXXXXXXXXX
				XXXXXXXXXXXXXXXX X X X X X X X X X X X XX
				XXXXXXXXX X XXX XXXXXXXX
					XXXXXXX XXXXXXXXXXXXXX
					XXXXXXXXX XXX XXXXXXXX XXX
				XXX
				XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
					XXXXXXXXXXXXXX X XXX XXXXXXXXXXX XXXXXXX
				XX
				XXXXXXXXXXXXXXX X XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX
			BBBBB			
		X
		
		XXXXXXXXXXXX
		XXXXXXXXXXXX XXXXXXX
		XXX XXXXXXX
		 XXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXX XXX X XXXX

		XXXXXXXX XXXXXXXXXXXXX
			XXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X XXXXX
			BB BBBBBBBBBBBBB XXXXXX XXXXXXXXXXXX X XXXXX XX XX XXXXX XXXXXX XXXXXX XXXXX
				XXXXXXXXXXXXXXXX X XXXXXXXXXXX  XXXXXX XXXXXXX XXXXX XXXXXXXXXXXXX
			BBBBB  XXXXXXXX XXXXX XXXXX XXXXXX XXXXXX			
		X
		XXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXX
			XXXXXXXXXX XXXXXXXXXX XXX XXXXX
			XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXX XXX XXXXXXX X XXXXXXXXXX XXX XXXXXXXX
			XXX XXXXXXXXXXX X XXX XXXXXXXX XXXXXXXXXX XXXXXX XXXX
			XXX XXXXXXXXXX X XXX XXXXXXXX XXXXXXXXXX XXXXXX XXXX
			XXX XXXXXXXXXX X XXX XXXXXXXX XXXXXXXXXX XXXXXX XXXX
			XXX XXXX X XXX XXXXXXX XXXXXXXXXX XXXXXXXXXXX
			XX XXXXXXXXX XXXXXXX XXXXXX X XXXXXXX XXXXXXX
			XX XXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXX XX XXXXXXX XXXXX
		XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
		XXXXX XXXXXXX XXXXXXX XXX XXXXXXXX XXXX XX XXXXXXXXXX XXXXXX XXXX
		XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX 
		X
			XX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXX XX XXXXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXXX
			XXXXXXXX XXXX X XXXXXX
			XXXXXXX XX XXXXXXX
			X
				XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBXX XXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
				XXX
			X
	
		X
		XXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX
		X
			XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXX
		X
		XXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
		X
			XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXX
			X
				XXXXXXXXXXXXXXXXX X XXXXXX
				XXXXXXXX X XXXXXX
			X
			XXXXXXXXXXXXX
			X
				XXXXXXXXXXXXXXXXXX X XXXXXX
				XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
				XXXXXXXXX X XXXXXX
			X
			XXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXX
		X
	XX
		XXXXXXXXX XXXXXXXXXXX XXXXX XX XXXXXX XX XXXXXX XXXX XXXXXX XXXXXXX XXXXXX XXXX
		XXXXXXXXX XXXXXXXXX XXXXXXX XXXXX
		XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
			XXXXXXXXX XXXXXXX XX XXXX XXXXXX XXXXXXXXXXXX XX XXXXXXX
			XXX XX X XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXX XXX XXXXXXXXXXX XX XXX X
			XXX XX X XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XX XXXXXXXXXX XXX XXXXXXXXXXX XX XXX X
			XXXXXXXXXXXXXXXXX X XXX XXXXXX XX  XXXXXXXX XXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXX
				XXXXXXXXXXXXX X XXX XX XXXXXXXXXX XXX XXXXXXXXXXX XX XXX X
				XXXXXXXXXXXXX X XX  XX XXXXXXXXXX XXX XXXXXXXXXXX XX XXX X
			XX
		XX
		XXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXX XXXXXXX XXX XXXXX XXXXXXX XXX
		XXXXXXXXX XXXXXXXXX XXXXXXX XXXXX
		XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXX XX XX  XX XXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXX
			X
				XXXX X XXXXXX  XX XXXXXXXXXXXXXX XXX XXX XXXXXXXXX
				XXXXXXXXXXXXXXXXX XXXXX XXXX X XXXXXXXX
			X
		XX
		XXXXXXXXX XXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXX XX XXXXXXX X XXXXXXXXXX XX XXXX XXXX XXX XXXXXXXXXXX X XXXXXX XXXXXXX XX XXXXXX XXXXX
		XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
		X
			XXX XXXXXXXXXX X XXXXXXXX XXXXX XXXXX XXXXXX XX
			XX XXXXXXXXXXXXXXXXXXX XX XX X XX XXXX XXXXXX XXX XX XXXXX XX XXXXX XXXXXXXXXXX XXXX
				XX XXXXX XX XXXXXXXX XX XXXXXXXXXXX X XX
					XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXX XXXXXXXX XXXX
					XXXXXXX
				X
				XX XXXXX XX XXXXXXX X XX XXXX XXXX
					XXXXXXXXXXXXXXX X XXXXXXXXXXXX XX XXXXXXXXXXX XXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXX X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XX XXXXXXXXXX X
				X
				XXXX XX XXXXX XX XXXXXXX XX XXXX XX XXXXXXX XX XXXX XX XXXXXXX X XXXXXX XXX XX XXXXX XX XXXXXXXXXXX XXXXXX XXXXXXX XX XXXXXX XXXXXX XXXXXXXXX XXX XXXXX XXX XXXXXXXXXXXXXX XXXXXX
					XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX
					XX XXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX X XXXX XXXXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXX X XXXXXXXXX
						XX XXXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXX X XXXXXX
						XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
						XXXXXXXXX X XXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXX X XXXXX
						XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXX
						XX XXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					X
				X
			X
			XXXXXXXXXXXXX XXXXX X XXXXXXXXX XXXXX XXXXXX XXX XXXXXX
			XXXXXXXX XXXXXXXXX XXX XXXXXX
			BB BBBBBBBBBBBBB
			XX XXXXXXXXX XXXX XXXX XXXXXX XXX
			XX XXXXXXXXXXXXXXXXXXX XX XX 
			X
				XX XXXXXX XXXX X XXXXXX
				XX XXXXX XX XXXXXXX 
				X
					XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XX XXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXXX
					X
						XXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXX X XXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXX X XXXXX
						XX XXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					X
				X
				XXXX XX XXXXX XX XXXXXXX XX XXXX XX XXXXXXX XX XXXX XX XXXXXXX 
				X
					XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
					XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX XXXXXXX XXXXXX XXXX X X XXXXXXXXX
					XX XXXXXXXXXX XX XXXXXXXXXXXXXXX 
					X
						XX XXXXXXXXXXXXXXX XX XXXXXXXXXX 
						X
							XXXXXXXXXXXXXXXXXXX X XXXXXX
							XXXXXXXXX X XXXXXX
						X
						XX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXX XXXX X X XXXXXXXXX
						X
							XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
							XXXXXXXXXXXXXXXXXX X XXXXXX
							XXXXXXXXX X XXXXXX
						X
						XXXXXXXXXXXXXXXXX X XXXXXX
						XXXXXXXX X XXXXXX
						XXXXXXXX X XXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXX X XXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XX XXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
					X
				X
			X
			BBBBB
			XXXXXXXXXXXXXXXXXXXXX XX XX XX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXX
			X
				XXXX X XXXXX
				XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX
				XXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXX
			X
			XXXXXX XXXXXX
		XX
		XX XXXXXXX XXXXXXXXXX XXXXXXXXX X XXXXXXXXXX XXXXX X XXXXXXXXXX XXXXXXXXXX X XXXXX XX XXXXXXXXXX XXXXXXXXX
		XXXXXXXX XXXXXXXXXXXXXXX
		X
			XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXX X XXX XXXXXXX  XX XXX XXXXX XXXXXXXXX XXXXXXXXX XXXXX XXXX
			XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX  XX XXXX XXXXXXXX XXXXXXXXX XXX XXXXXXX XXX XXXXXXXXX XXXX
			XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX XXXXXX XXXX XXX
										XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX XXXXX XXXX XXX
									XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXX X XXXXXX
			XXXXXXXXXXXXXXXX X XXXXXXXXXX  XX XXXXXXXXX XXXXXXXXX X XXX XXXXXXXXXXX XX
		X
		XX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX
		XXXXXXXX XXXXXXXXXX
		X 
			XXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXX X XXX XXXXXXX
			XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXX XXX
									XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXX XXX
									XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXX X XX
			XXXXXXXXXXX X XXXXXXXXX
		X
		XX XXXXXXX XXXXXXXXXX XXXX X XXXXXXXXXXXX XXXXX X XXXXX XXXXXXXXXX X XXXXX XX XXXXXXXXXX XXXX
		XXXXXXXX XXXXXXXXXXXXXXX
		X 
			XXXXX X XXXXXX  XX
			XXXXXXX X X XX X X XXXXXXXXXXXXXX XXXXX
				XXXXX X XXXXXXXXXX XX
				XXX	XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XX
					XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXX XX
					XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX
				X
					XXXXX X XXXXXXXXXX
					XXXXXX
				X
			X
			XXXXXXXXX
			X
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXX X XXXXXX
			X
			XXXX X
				XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXX XXXX XXX XXXXXXXXX XXXX
				XXX XXXXXXXXXX  XX XXXXXXXXX XXX XXXXXX XXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX  XX XXX XXXXX XXXXXXXXXX XXXX XXX X XXXX
					XXXXXXXXX X XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX X X XX XX XXXXXX XXXXXX XXXX
					XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX XX XXXX
				X
				XXXX X XX XXXX X XXXXX XX XXXXXXXXXXX XXXXX
					XXXXXXXXX X XXX XXXXXXX  XX XXX XXXXXX XXXXX XXXXX XXXX
					XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX  XX XXXX XXXX X XXXXX XXXXXXX X XXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX XXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXX XXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXX XXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXXXXXXXXXXX X XXX  XX XXXXX XXXX XXXXXXX
				XXXXXXXXXXXXXXXXXXXXX X XXX XX
				XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XX
				XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXX
			X
			XXXXXXXXXXXXXXXX X XXXXXX
		X
		XXXXXXXXX XXXXXXXXXX XXXXXX XXXX X XXXXXXXXXXX XXXX X XXXXX XXXXXXXXXX X XXXXX XX XXXXXXXXXX XXXX
		XXXXXXXX XXXXXXXXXXXXX
		X
			XXXXXXXXXXXXXXXXXXXXXX  XX XXXXXXXXX XXXX XXX XXXX
			XXX X X XXXXXXXXXXXXXX  XX XXXXXXXXXX XX XX XXXXXXX XX XXXXX XXX XXXXXXXXXX XX X
			XXX X X XXXXXXXXXXXXXX  XX XXXXXXXXXX XX XX XXXXXXX XX XXXXX XXX XXXXXXXXXX XX X
			XXX XXXXX X XXXXXXXXXXXXXXXXXX XXXXXX XXXX
				XXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX
				XXX XXXXXXXXX  XX XXXXXXXXXX XXX XXXXXXXX XXXXXX XXXX
				XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX  XX XXX XXXXX XXXXXXX XX XXXXX XXX XXXXXXXXXX XX XXXX XXX XX XX
				XXX XXX X XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
				XXX XXXXXXXX X XBBBBBB BBBBBBBX X XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXXX XX XXXXXX XXXX X XXXXX
				XXXXXXXXXXXX XX X XX XXXXXXXXXXXXXXXXX XXX XXXXX
				X
						XXXXXXXX X XXX XXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXX X X XXXXXXXX XXXXXX X XXXXXXXXXXXXXX
				X
				XXXX XXXXXXXXXXXX XX X XX XXXXXXXXXXXXXXXXX XXX XXXXX
				X
						XXXXXXXX X XXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
				X
				XXXXXXXXXXXX XX X XX XXXXXXXXXXXXXXXXX XXX XXXXX
				X
						XXXXXXXX X XXX XXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXX
				X
				XXXX XXXXXXXXXXXX XX X XX XXXXXXXXXXXXXXXXX XXX XXXXX
				X
						XXXXXXXX X XXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
				X
				XXXXXXXXXXXX XX X XX XXXXXXXXXXXXXXXXX XXX XXXXX
				X
						XXXXXXXX X XXX XXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXX X XXXXX
				X
				XXXX XXXXXXXXXXXX XX X XX XXXXXXXXXXXXXXXXX XXX XXXXX
				X
						XXXXXXXX X XXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
				X
				XXXXXXXXXXXXX X XXXXXXXXXXXXXXX X XXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXX XX XXXXXXX XXX XXXXXXXXX XX XXXXX XXXXXX XXXX
				X
						XXXXXXXXXXXXXXXXXXXX X XXXXXXXX	 XX XXXX XX XXXX
					XXXXXXXXXXXXXXXXXXXX X XX  XX XXXXXXXXXX XXXXXXX XXXXX XX XXXX
				X
				XXXXXXXXXXXXXXXXXX X XXXXXX XX XXXX XXXXX XXXXXXXX X XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
				XXX XXXX X XXX XXXXXXXXXXXX  XX XXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXX
				XXXXXXXXXXXX X XXXXXXXXXXXXXXXXX  XX XXXXXXXXXXXX XXXXX XXX XXXX
				XXXXXXXXXXXXX X XXX XXXXXXXX X X XXXXXXX X XXXXXXXXXXXXX X XXX  XX XXX XXXX XX XXXXXX XXXXXXXXXX
				XXXXXXXXXXXXXXXXXX X XXXXX  XX XXXXXXXXXXX XXXXX
				XXXXXXXXXXXXXX X XXXXXXXXX XX XXXXXXXXX XXXX X XXXXXXXXXXXX XX

			X	

			XXXXXXXXXX XXX XXXXXXX XX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXXX XXX XXXXXXXXX XXXX XXX XXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXX XXXX X XXXXXX
				XXXXXXX XX XXXXXXX
				X
		
						XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXXXXX
				X
				XXXXXXX XX XXXXXXXX
				X
					XXXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXXXX
						XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXX
				X
			XXX

			XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
					XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXXX
			XXX

			XXXXXXXXX XXX XXXXXXXXXXX XXXXX XX XXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XX XXXXXX XXXXXXXXXXX XXX X XXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XX XXXXXXXXX XX XXXXXXX
				XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX X XXXXXX XXXXXX XXXXXXX XX XXXXXXXXX XXXXXXX X XXXXX
				XXXXXXXXX X XXXXXX XXXXXXX XXXXXXXXXX XXXXXXX XX XXXXXX XXXXXXX XXXXX XXXX XXXXXXXXX X XXXXX
				XXXX X XXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXX XXX XXXXXXXXXXX XXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXX

			XXXXXXXXX XXX XXXXXX XXXX XXX XXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXXXXXXX X XXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XX XXXXXX XXXXXXXX XXX X XXXXXXXXXXXX
				XXXXXXXX XXXX X XXXXXX XX
				XXXXXXX XX XXXXXXX XXXXXX X XXXXXXXXX XXXXXX XXXXX XX XXX XXXX XXXXXXXXXXX XX
				X
					XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXX XXXXXXX XX XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXX XX XXXXXX X  XXXXXXXXXX XXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXX XXXXXXXXXX XX XX XXX XXXXXXX XX XXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXXXX XXXXXXXXXX XX XX XXX XXXXXXX XX XXXXX
						XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
					XXX
				X
				XXXXXXX XX XXXXXXXXXXXXXX X XXXXXXXXX XXXXXXX XXXXXX XX XXX XXXXX XXXXXXXXXXX XX
				X
					XXXXXXXXXXXX XX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXX
						XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX XXXXXXXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
					XXX
				X
				XXXXXXX XX XXXXXXX
				X
					XXXXXXXXXXXX XX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX
						XXXXXXXXXXXXXXXXXXXXXX
						XXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBXX XXXXXXXXXXX
						XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
					XXX
				X
				XXXXXXX XX XXXXXXXX
				X
					XXX XXXX
					XXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXX
						XXXXXXX
					X
					XXXX XXXXXXXXXXXXXXX
							XXX X XXXXXXXXXXXXXXXXX
					X
					XXXX XXX X XXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
					XXX
				X
			XXX
			XXXXXXXXX XXX XXXXXXXXXXXXXX XXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXX XX XXXXXX X XXX X XXXXXXXXXXXXX
				XXXX X XXXXXX XXXXXX XX XXXX
				XXXXXXXX XX XXXXXX XXXXXXXXXXX XXXX X XXXXX
					XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXX XXXXXXXXXX XXXXX XXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXX X XXXXX XXX XXXXX XXXXXXX
				X
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXX
			XX XX XXXXXXX XXX XXXXXXXX XXXXXX
			XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XX XXXXXX X XXX X XXXXXXXXXXXXXX
				XX 	XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXXXXXXXXX
				XX 	XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX X XXXXXXXXXX XXX
				XX 	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXX XXXXXX XXXXXXXXX
			XX XXX
			XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XXXX XXXX XXXXXXX XX XX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXX XX XXXXXX X XXX X XXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XX XXX XXXXXXXXX XXXXX XXXXX
					XXXXXXXXXXXXXXXXX X XXXXXX XXXXXX XXXXX XX XXXXX XXXXX XXXXX
					XXXXXXXX X XXXXXX XXXXXX XXXXX XX XXXXX XXXXX XXXXX
				X
				XXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXX X XXXXXX XXXXXX XXXXX XX XXXXX XXXXX XXXXX
					XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXX XXXX XX XXXXXXXXXXX
					XXXXXXXXX X XXXXXX XXXXXX XXXXX XX XXXXX XXXXX XXXXX
				X
				XXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXX
			XXXXXXXXX XXXXXXXX XXX XXXXXXX XX XXXXXX XXXXXX X XXXXXX XXX XXXXXXXXX XXXXX XXXXX XXXXXXXX XXXXXXX X XXXX
			XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
				XXX XX X XXX XXXXXXXXX XXXXXXXXXX
				XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXX X XXXXXXXX XXXXXX
				XX X XXXXXXXXXXXXXXXXXXX  XX XXX XXXXXXX XX XXXXXX XXXXX XXXXXXXXXX XXXXXXX XX XXXX
				XXXXXXXX  XX XXXXX XXXX
					XXXXXXXXXXX XXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
					XXXXX XXXXXXXXXXXXXXXXXXXX
					XXXXX XXX XXXX XX XX XXXXXXXXXX
					XXXXX XXXXXXX  XX XXX XXXX
					XXXXXX XXXXX XXXXXXXXXXXXXXX
					XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXX XX XXXXXXXXX XX XXXX XXXXXXX XX XXXXXX
					XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XX XXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXX X XXXX
						XX XXXXXXXXXXXXXXXXX
						XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
						XXXXXXXXXXXXXXXXXXXXX X XXX X
						XXXXX XX XXXXXXXXXXXXXXXXXXXX
							X
								XXXXXXXXXXX
								XXXXXXXXXX
								XXXXXX XXXXXX
							X
						XXXXXXXXXXXXXXXXXXXXXX
							XXXXXXXXXXXXXXXXXX	 XX XXXXXXXXX X XXXXXXX XXXXXXXXXX XXXXX
						X
					X
				XXX
				XXXXXX XXXXXX
			XXX
			XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
				XX XXX XXXXXX X XXXXXXXXXX
				XX XXX XX X XXX XXXXXXXXX
				XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
				XX X XXXXXXXXXXXXXXXXXXX  XX XXX XXXXXXX XX XXXXXX XXXXX XXXXXXXXXX XXXXXXX XX XXXX
				XXXXXXXX  XX XXXXX XXXX
					XXXXXXXXXXX XXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXX
					XXXXX XXXXXXXXXXXXXXXXXXXX
					XXXXX XXXXXXX  XX XXX XXXX
					XXXXXX XXXXX
					XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXX XX XXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXX X XXXX
						XX XXXXXXXXXXXXXXXXX
						XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX
						XXXXXXXXXXXXXXXXXXXXX X XXX X
							XXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
						X
						XXXXXXXXXXXXXXXXXXXXX X XXX X
							XXXXX XX XXXXXXXXXXX XX XXX XXXXXXX XX XXXXXXXX XXXX XXXXX XXXXXXX XXXXXXXXXX XXXX
							X
								XXXXXXXXXXXXXXXXXXXX
								XXXXXXXXXXXXXXXXX XXXXXX
							X
							XXXXX XX XXXXXXXXXXXXXX  XX XXXXX XXXXXXX XXXXXXXXX XXXX
							X
								XXXXXXXXXXX
								XXXXXXXXXX
								XXXXXXXXXXXXXXXXX XXXXXXXXX
								XXXXXX XXXXXX
							X
							XX XXXXX XX XXXXXXXXXXXXXXXXXXXX
							XX X
								XX 	XXXXXXXXXXX
								XX 	XXXXXXXXXX
								XX 	XXXXXX XXXXXX
							XX X
						XXXXX XX XXXXXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXX XXXX
								XXXXXXXXXXX
								XXXXXXXXXX
								XXXXXX XXXXXX
							X
							XXXXX XX XXXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX
								XXXXXXXXXXXXXXXXXXXXXX
							X
							XXXXX XX XXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX
								XXXXXXXXXXXXXXXXXXXXX
							X
							XXXXX XX XXXXXXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX
								XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
							X
							XXXXX XX XXXXXXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXX XXXXXXXXX
								XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							X
							XXXXX XX XXXXXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX
								XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							X
							XXXXX XX XXXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXXXX XXXX
								XXXXXXXXXXXXXXXXXXXXXX
							X
							XXXXX XX XXXXXXXXXXXXXXX
							X XX XXXXX XXXXXXX XXXXXXXX XXXX
								XXXXXXXXXXXXX
								XXXXXXXXXXXX
								XXXXXX XXXXXX
							X
							XXXXXXXXXXXXXXXXXXXXXX
								XXXXXXXXXXXXXXXXXX	 XX XXXXXXXXX X XXXXXXX XXXXXXXXXX XXXXX
						X
					X
				XXX
				XXXXXX XXXXXX
			XXX
			XXXXXXXXX XXX XXXXXXX XX XXX XXXXXXXX XX XXX XXXXXXXX
			XXXXXXXX XXXXXXXXXXXXXX XXXX X
				XXX XXXX X XXX X XXX X XXXXXXXXXXXXX X XXXX X XXX X XX
				XXXX X XXXXXXXXXXXXXXXXX
					XXXXXX XXXXX
			X
			XXX XXX X XXX
			XXX XXXXXXX X XXX
			XXX XXXXXXXXX X XXX
			XXX XXXXXXXXX X XXX
			BBB BBBB BB B
				XXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXX
			BBBBBB
			XXXXXXXXX XXX XXXXXXXXX XXXXXXXXX X XXXXXXXX XXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXX X
				XXXXXXXX XXXXXXXXXXX
					XXXXXXXX XXXXXXXXX
						XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX 
					X
					XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
				    XXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXX
				        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXX XXXXXX XXXXXX
				    X
				    XXXXXX XXXXX
				X
				XXX XX X XXX 
					XX X XXX
				XXX XX X XXXXXXXXXXX 
					XX X XXXXXXXXXXX
				XXX XXXX X XXXXXXXXXXXX 
					XXXX X XXXXXXXXXXXX  
				XX XXXXXXXXXXXXXXXX XXX XXX XXXXXX X
					XXXXXX XXX
				X
				XXXX XX XXXXXXXXXXXXXXXX XXX XXX XXXXX X
					XXXXXX XXX
				X 
			X

			XXXXXXXXX XXXXXXXXXXXXXX 
			XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
				XXXXXXX XX XXXXXXX  XXXXXXXXXXXXXXXX XXX XXXX
				X
					XXX XXXXXXX X X
						XXXXX XXXXXX
						X
							XXXXXXX XXXXXX
							X
								XXXXXXXXXX XX XXXXX XXXXXXX XXXX
								XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX
								XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XX XXXXXXXXX
								XXX XXXXXXXXXXXXXXXX XXXX
								XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
								XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
								XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
								XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
								XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
								XXXXXXXXXX XXXXXXXX XXXX X X XXXXXXXXXXX X X XXXXXXXXXXXXX X X XXXX
							X
						X
					XX
					XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
				X
			XXX
			
			XXXXXXXX XXXXXXXXXXXXXXXXXXX
			X
				XXXXXXX XX XXXXXXX
				X
					XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX
					X
						XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXX XXXXXX XX XX XXXXXX XXX XXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX XX XXX XXXXXXXXX
						XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX
						X
							XXXXXXXXX
								XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
							XXXX
								XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX XXXXXX
						X
						XXXXXXXX X XXXXXXXXXXXXXXXXXX
					X
				X
			X

			XXXXXXXXX XXX XXXXXXXXXXX XXXX X X XXXXXXXXXXXXXXXX X XXXXX XXXX XXXXX XXXXXXXXXXXX
			XXXXXXXX XXXXXXXXXXXXXX XXXXXX
			X
				XX XXXXXXXXXX XXXXX X
				X X XXXXXXXXXXXXXXXXXXXX
				XX XXXXXXXXXX XXXXX X
				X X XXXXXXXXXXXXXXXXXXXX 
				XXXXXXXX XXXXX XXXXXXX
				XXXXXXXXXXX XXX XXXXXXXXXXXXX XXX XXXXXXXXXXX XXXX
				XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX 
						XXXXXXXXXXXXX X XXXXXX XX XXXXXXX XXXXXXX XXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXX XXXXXXX X XXXXXX X XXX XX XXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXX
						XXXXXXXXX XX XXXXXXXX  XX XXXXXXXXXXX XXX XXXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XX XXXXXX XXXX XXXXXXXXX XX XX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX XX XXXXX XXXX XXXXXXXXX XX XX
						X
						XXXXXXXXX XX XXXXXXX XX XXX XXXXXXXXX XXXXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
						X
						XXXXXXXXX XX XXXXXXXX XX XXX XXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
							X
								XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
							X
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX
							X
								XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									XXXXXXXXXXXXXXXXXXXXXX X XXXXXX
								XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
							X
						X
						XXXXXXXXXXXXXXXXXX X XXXXXXXX
						XXXXXXXXXXXXXXXXXX X XXXXXXXX
				XXX
			X

			XXXXXXXXX XXX XXXXXXXX XXXX XXX XXXXXXXXXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXX
			X
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XX XXXXXXXX XXXX XX XX
				XXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX XXXXXXXXXX
			X

			XXXXXXXXX XXXXXXXX XXXXXXXXX XXXXX XXXXXX XXXXXXXXX XXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXXX
			X
				XXXXXXXXXXXXXXXXXXXXXXXXXX  XX XXXXXXXX XXXXXXXXX XX XX
				XXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXX X XX
				XXXXXXXXXXXXXXXXXX XXXXXXXXXX
			X
			XXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX
			XXXXXXXX XXXXXXXXXXXXX
			X 
				XXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXXXXXXXXXX
				XXXXXXXXXXXXXXXXX XXXXXXXXXX
			X

			XXXXXXXXX XXXXXXXX XXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXX XXXXXX
			XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX
			X 
				XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX XXXXXXXXXXXXXXXXX
				XXXXXX XXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXX XXXXXXXXXX
			X

			XXXXXXXXX XXXXXXX XXXX
			XXXXXXXX XXXXXXXXXXX
			X
				XXXXX X XX X X XXXXXXXXXXXXXX XXXX
					XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
			X

			XXXXXXXXX XXXXXXX
			XXXXXXXX XXXXXXXXXXXXXX
			X XX X
				XXXXX X XX X X XXXXXXXXXXXX XXXX X
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
				X
			X

			XX XXX XXXXXXX XXXXXX XXXXXXXXX XX XXXXXXXX X XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXX XXXXX
			XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX 
				XXX XXXXX X XXXXXXXXXXXXXX
				XXXXXXXX XX XXXX
					XXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX
					X
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
					X
					XXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXX
					XXXXXXX
				X
				XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBX X XXXXXX XXXXXXXXXXXXXXX
					XXXXXXXXXXXX
					XXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
					X
						XXXXXXXXXXXXXXXXXX
				XXX
			XXX

			XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXX X XXXXXX
				XXXXXXXXXXXX
				XXXXXXXX XX XXXXXX X
					XXXXXXXXXXXXXXXXXXX X XXXXX
					XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
				X
				XXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXX
				XXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXXX
				XXXXX XX XXXXXX XXXXXXXXXXXXXXXX X XXXXXX
				XXXXXXXXXXXXXX X XXXXX
				XXXX X XXXXXXXXXXXXXX
				XXXXXXX XX XXXXXXXX
				X
				XXXX XXXXXXX XX XXXXXXXXX
					XXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXX
					XXXXXXXXXXXXXX X XXXXXX
				X
				XXXX XXXXXXX XX XXXXXXXX
					XXXXX XX XXXXXX XXXXXXXXXXXXXXXX X XXXXX
					XXXXXXXX XX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
								XXXXXXXXXXXXXXXXXXX X XXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
						X
					XXXXXXXXXXXXXX X XXXXXX
				X
					XXXX XXXXXXX XX XXXXXXXXX
					XXXXXXXX XX XXXXXX
						XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
								XXXXXXXXXXXXXXXXXXX X XXXXXX
							XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX
						X
					XXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXXXX
					XXXXXXXXXXXXXX X XXXXXX
				X
				XXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXXX X XXXXXX
				XXXXXXXXX X XXXXXX
				XXXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXX
			XXX

			XXXXXXXXX XXX XXXXXXXX XXXXXXXX X XXXXX XXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX XXXX XXXXXXXXXX X XXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXX XXX
				XXXXXXXXX
					XXXX X XXXXXX
				X
				XXXXX XXXX
				XXXXXXX XX XXXXXXX
				X
					XXXXXXXXXX XXXXXXXXX XXXX
					XXXXXXXXXXXX
					X
						XXXXXXXXXX XXXXX XXX XXXXXXXX XXXX
						XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXX X XXXXXXXXX
					X
					XXXXXXX XXXXXX XX XXXXXXXXXX
					XXXX XXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXX XXXXXXXXX
				XXXX XXXXXXX XX XXXXXXXX X
					XXXXXXXXXX XXXXXXXXX XXXXXXXXX
					XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXX XXXX X X XXXXXXXXX
					X
						XXXXXXXXXX XXXXX XXX XXXXXXXX XXXXXXXXX
						XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXX X XXXXXXXXX
					X
					XXXX XXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXX XXXXXXXXX XXXXXXXXXX
				XXXX XXXXXXX XX XXXXXXX X
					XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXX
					XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXX XXXX X X XXXXXXXXX
					X
						XXXXXXXXXX XXXXX XXX XXXXXXXX XXXXXXXXX XXXXXXXXXX
						XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXX X XXXXXXXXX
					X
					XXXX XXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXX XXXXXXXXX
				XXXX XXXXXXX XX XXXXXXXX
				X
					XXXXXXXXXX XXXXXXXXX XXXXXXXX
					XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXX XX XXXXXXX XXXXXX XXXX X X XXXXXXXXX
					X
						XXXXXXXXXX XXXXX XXX XXXXXXXX XXXXXXXX
						XXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
						XXXXXXXXXXXXXXXX X XXXXXXXXX
					X
					XXXX XXXXXXXXXXXXXXXXXXXXXX
				X
			XXX


			XXXXXXXXXX
			XXXXXXXXX XXXXXX XXXXX XXXXXXXXXX
			XXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXX XXXXXXX XXXX
			XXXXXXXXXXXX XXX XX XXXXX XX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX X
			XXXXX X XXXXXX XX XXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXX
			XXXXXX X XXXXXXX  XXXXXXXXXXXX XX XXXXXX X XXXX XXXXXXX XXX XXXXXXX XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXX XXXXXXXX
			XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX X XXXXXXXX XXXXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
			XXXXXXXX XXXXXXXXXXXX XXXXX XXX XXX XXXXX XXXXXX XXXXXXXX
			XXXXXX XXXXXXXXXXXX XX XXXX XXXXXXX XX XX XXXXX XXXXXXXXXXXX X XXXXXX X XXXXXXXXXXX XXX XXXXXXXX XXXXX XXXX
			XXXXXXXX XXXXXXXXX X  XXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX XXXXXX XXX XXXXXXX XXXXXXXX X XXXX XXXXXXX
				XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX XXXXXXXXXXXXXXX  XX XXXXXXXX XXXXXXXXXXXXX XXXXX XXXX
						XXXXX X XX X X XXXXXXXXXXXX XXXX X XXXXX XXXXXXX X XX X XX XXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXX XXXXXX XXXXXXX
							XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXX X XXXXXXXXX XXX XX XXXXX
							XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
							XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XX XXXXXXXXX XXXXXX XXXX XXX XXXX XXXXXXXXXXX XXXX
						X
						XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX XXXXXXXXXXXXXXX  XX XXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXX
							XXXXX X XX X X XXXXXXXXXXXX XXXX X XXXXX XXXXXXX X XX X XX XXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXX XXXXXX XXXXXXX
								XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXX XXXXXX X XXXXXXXXX XXX XX XXXXX
							X
							XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX XXXXXXXXXXXXXXX  XX XXXXXXXX XXXXXXXXXXXXX  XXXXX XXXX
								XXXXX X XX X X XXXXXXXXXXXX XXXX XXXXXX XXXXXXX X XX X XX XXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXX XXXXXX XXXXXXX
									XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXX XXXXX XXXXXXXXXX X XXXXXXXXX XXX XX XXXXX
								X
								XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX XXXXXXXXXXXXXXX  XX XXXXXXXX XXXXXXXXXXXXX  XXXXX XXXXXXXXX XXXXXXXXXX
									XXXXX X XX X X XXXXXXXXXXXX XXXX XXXXXX XXXXXXX X XX X XX XXXXX XXXXXX XXXXXX XXXXXXXXXXXX XXX XXXXXX XXXXXXX
										XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXX X XXXXXXXXX XXX XX XXXXX
									X
									XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XX XXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXX XXX XXXXXXXXX XXXXXXXXXXXXXX
								XXXXXXXXXXXXX XXXXXXXX
							XXXXXXXXXXXXX XXXXXXXX
						XXXXXXXXXXXXX XXXXXXXX
				XXXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXX XXXXXXX

			XX XXXXXXX XXXXXXXXXXXXX XXXXXXXX
			XXXXXXXX XXXXXXXXXXX
			X  
				XXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX XXXXXXXXXXXXXXX
					XXXXX X XX X X XXXXXXXXXXXX XXXX X
						XXXXXXXXXXXXXXXXXX
					X
					XXXXXXXXXXXXXXXXXXXX
				XXX
			X
			XXXXXXXXX XXXXX
			XXXXXXXX XXXXXXXXXX
			X
				XXXXXXXXX XXX XXXX X XXXXX X XXXXX
				XXXXXXXX XX XXXXXX X 
					XXXXXXXXXXXXXXXXXXXXX
					XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXXXXXX XXX XXXXXXXXX
				XXXXXXXXX XX XXXXXXX X
					XXXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXXXXXX XXX XXXXX
				XXXXXXXXX XX XXXXXXX X
					XXXXXXXXXXXXXXXXXXXXXXX
				X
				XXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXX
				XXXXX X XXX
				XXXXXX X XXX
				XXXXXX X XXX
				XXXXXX X XXX
			X

			XXXXXXXXX XXXXXXXXXXXX XXXXX
			XXXXXXXX XXXXXXXXXXXX
			X
				XXXXXXXXX XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
				XXXXXX X XXX
				XXXXXX X XXX
			X

			XXXXXXXXX XXX XXXXXXXXXX XXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			X
				XXX X X XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
				XXX XXXX X XXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXX X XX X XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXXX X XXXXXXXXX
					XXXX XX XXXX XXXXXXXXXXXXXXX X X X XXXX  XX XXX X XXXX XXXXXXXX XXXXXXXXXXX
				X
				XXXX X
					XXXX XX XX XXXXXXXXXXXXXXX X X X XXXX  XX XXX X XXXX XXXXXXXX XXXXXXXXXXX
				X
			XXX

		XXX
XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBB
	XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
	BB BBBBBBBBBBBBB
		XXXX XXXX XXXXXXXXXXXX X XXXX XX XXX XXXXX XXXXXXXXX XXX
		XXXX XXXXXXXXXXXXXX
			XXX
				 XXXXXXX XXXXXXXXXX
					XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
					XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
					XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
					XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
				XXXXXXXXX				XXXXXXX

				XXXXXXXX
			XXXX
			XXX
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
				XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX
		XXXXXX
		XXXX XXXXXXXXXXXXXXXXXX
	BBBBB
XXXX 
	XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
		XXXXX
			XX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXX XXXXXXXXXXXXXXXX
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXXXXXX
				
			XXXXXX
			XXXX XXXXXXXXXXXXXXXXX
				
			XXXXXX

		XXXXXX
	XXXXXX XXX
	XXXX XXXXXXXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXX
			XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
			  XXXX XXXXXXXXXXXXXXXXXXXXX

			XXXX XXXXXXXXXXXXXXXXX	
			XXXXXX
			XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX			

		XXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXX
XXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXX

		BB BBBBBBBBBBBBB
			XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
			XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		BBBBB
		XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
		XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXXX
	XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
		XX XXXXXXBBB BBBBBBBBBBBBXX
			XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XX
		XXXX
		BB BBBBBBBBBBBBB
			XX XXXXXXBBB BBBBBBBBBBXX
				XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
			XXXX
		XXXXXX
	BBBBB
BBBBBBBB